on:
  workflow_dispatch:
  push:
    branches: main

name: Blag to my blag

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'DNR')"
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  verify-mastodon:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Find and replace href
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<a href=\"https://quinnwitz.house/@magsol\" class=\"about-link\">"
          replace: "<a rel=\"me\" href=\"https://quinnwitz.house/@magsol\" class=\"about-link\">"
          regex: false
          include: about.html
      - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit about.html -m "Added rel=me attribute to Mastodon link."
      - name: Push changes back
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
